# Generated by Selenium IDE

from selenium import webdriver
from selenium.webdriver.common.by import By

class TestHttpsdemoqacom():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_httpsdemoqacom(self):
    self.driver.get("https://demoqa.com/")
    self.driver.set_window_size(1936, 1066)
    self.driver.find_element(By.CSS_SELECTOR, ".card:nth-child(2) svg").click()
    self.driver.find_element(By.CSS_SELECTOR, ".element-group:nth-child(2) .header-wrapper").click()
    self.driver.find_element(By.CSS_SELECTOR, ".element-group:nth-child(2) .header-wrapper").click()
    self.driver.find_element(By.CSS_SELECTOR, ".element-group:nth-child(1) .header-wrapper").click()
    self.driver.find_element(By.ID, "item-0").click()
    self.driver.find_element(By.ID, "userName").click()
    self.driver.find_element(By.ID, "userName").send_keys("Hello")
    self.driver.find_element(By.ID, "userEmail").click()
    self.driver.find_element(By.ID, "userEmail").send_keys("test@gmail.com")
    self.driver.find_element(By.ID, "currentAddress").click()
    self.driver.find_element(By.ID, "currentAddress").send_keys("hetmana st. 65/96")
    self.driver.find_element(By.ID, "permanentAddress").click()
    self.driver.find_element(By.ID, "permanentAddress").send_keys("Privet!")
    self.driver.find_element(By.ID, "submit").click()
    self.driver.close()
  
